---
AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
Layout/ElseAlignment:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true
Layout/EmptyLines:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
Layout/EndOfLine:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/Tab:
  Enabled: true
Layout/TrailingBlankLines:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/EndAlignment:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Max: 120
Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
Style/Alias:
  Enabled: true
Style/PreferredHashMethods:
  Enabled: true
